[package]
name = "hardware"
version = "0.1.0"
authors = ["Aidan T. Manning <periodicaidan@gmail.com>"]
edition = "2018"

[features]
default = ["std"]
std = []
alloc = []

[dependencies]
bitmatch = "0.1.0"
lazy_static = "1.4.0"